# Backup

version: '3'

networks:
  default:
    name: gateway
    external: true
    driver: bridge

volumes:
  grafana:
  prometheus:
  postgres:

services:
  grafana:
    container_name: grafana
    expose:
      - 3000
    ports:
      - '3000:3000'
    image: grafana/grafana:latest
    user: '0'
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/coti.svg:/usr/share/grafana/public/img/grafana_icon.svg:rw
      - ./config/grafana/favicon.png:/usr/share/grafana/public/img/fav32.png
    environment:
      # Note: may need to rm (refresh) the grafana volume when changing these
      GF_SERVER_DOMAIN: ${SERVERNAME}
      GF_SERVER_ROOT_URL: https://${SERVERNAME}/monitoring
      # GF_SERVER_
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: false
      GF_INSTALL_PLUGINS: yesoreyeram-infinity-datasource
      # DB Config
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgres:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: postgres
      GF_DATABASE_PASSWORD: internal_password
      GF_DATABASE_SSL_MODE: disable
    depends_on:
      - prometheus
      - postgres
    networks:
      - default

  loki:
    container_name: loki
    image: grafana/loki:2.7.3
    volumes:
      - ./config/loki:/etc/loki
    restart: unless-stopped
    command: -config.file=/etc/loki/config.yaml

  promtail:
    container_name: promtail
    image: grafana/promtail:2.7.3
    volumes:
      - /var/log:/var/log
      - ./config/promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

  nodeexporter:
    image: prom/node-exporter:v0.18.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus
    volumes:
      - ./config/prometheus:/etc/prometheus
      # - prometheus:/prometheus # Makes lose data when you destroy containers
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  # DB for Grafana
  postgres:
    container_name: postgres
    image: postgres:15.1
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: grafana
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: internal_password
