{
 "title": "Coti Public (Systemd)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"nodeexporter:9100\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\",mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"nodeexporter:9100\"} / (node_memory_MemTotal_bytes{instance=~\"nodeexporter:9100\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"nodeexporter:9100\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"nodeexporter:9100\"} + 1))) * 100 + 0.1",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"nodeexporter:9100\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"nodeexporter:9100\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"nodeexporter:9100\"}",
     "legendFormat": "15m"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{instance=~\"nodeexporter:9100\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU cores"
    }
   ]
  },
  {
   "title": "Network bandwidth usage per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~'nodeexporter:9100',device=~\"eth0\"}[$__interval])*8",
     "legendFormat": "{{device}}_transmit"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~'nodeexporter:9100',device=~\"eth0\"}[$__interval])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"nodeexporter:9100\", mode='system'})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"nodeexporter:9100\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Logs Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Requests in the last hour",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"nginx\"} != \"monitoring\" != \".env\" != \"acme\" | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <_> <_> \"<_>\" <_>` [1m])) by (path)"
    }
   ]
  },
  {
   "title": "Disk IOps Completed（IOPS）",
   "type": "graph",
   "description": "Read/write completions per second\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"nodeexporter:9100\"}[2m])",
     "legendFormat": "{{device}}_Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"nodeexporter:9100\"}[2m])",
     "legendFormat": "{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Web Server Log Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"nginx\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <_> <_> \"<_>\" <_>` [1m])) by (status)",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Coti Node Log Count",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({filename=\"/var/log/coti-node.log\"}[2m]))\n\n",
     "resolution": 2
    }
   ]
  },
  { "title": "Networking Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU% Basic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\",mode=\"system\"}[30s])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\",mode=\"user\"}[30s])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\",mode=\"iowait\"}[30s])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\",mode=\"idle\"}[30s])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "graph",
   "description": "Sockets_used - Sockets currently in use\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_alloc - Allocated sockets\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nRetransSegs - TCP retransmission packets\n\nOutSegs - Number of packets sent by TCP\n\nInSegs - Number of packets received by TCP",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'nodeexporter:9100'}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'nodeexporter:9100'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~'nodeexporter:9100'}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~'nodeexporter:9100'}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'nodeexporter:9100'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{instance=~'nodeexporter:9100'}[2m])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{instance=~'nodeexporter:9100'}[2m])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~'nodeexporter:9100'}[2m])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  }
 ]
}