{
 "title": "Public Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"nodeexporter:9100\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\",mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"nodeexporter:9100\"} / (node_memory_MemTotal_bytes{instance=~\"nodeexporter:9100\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'nodeexporter:9100',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'nodeexporter:9100',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~'nodeexporter:9100',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~'nodeexporter:9100',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'nodeexporter:9100',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"nodeexporter:9100\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"nodeexporter:9100\"} + 1))) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "CPU% Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\",mode=\"system\"}[30s])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\",mode=\"user\"}[30s])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\",mode=\"iowait\"}[30s])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"nodeexporter:9100\",mode=\"idle\"}[30s])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"nodeexporter:9100\", mode='system'})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"nodeexporter:9100\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Popular Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "{container_name=\"traefik\"} |= \"Request=\" != \"monitoring\" | pattern `<_> Request=\"<request>\"`"
    }
   ]
  },
  {
   "title": "Latest Transactions",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 9 },
   "targets": [
    {
     "columns": [
      { "selector": "attachmentTime", "text": "attachmentTime", "type": "timestamp_epoch_s" },
      { "selector": "amount", "text": "amount", "type": "number" },
      { "selector": "createTime", "text": "createTime", "type": "timestamp_epoch_s" },
      { "selector": "hash", "text": "hash", "type": "string" },
      { "selector": "index", "text": "index", "type": "number" },
      { "selector": "isValid", "text": "isValid", "type": "string" },
      { "selector": "leftParentHash", "text": "leftParentHash", "type": "string" },
      { "selector": "rightParentHash", "text": "rightParentHash", "type": "string" },
      { "selector": "senderTrustScore", "text": "senderTrustScore", "type": "number" },
      { "selector": "transactionConsensusUpdateTime", "text": "transactionConsensusUpdateTime", "type": "string" },
      { "selector": "transactionDescription", "text": "transactionDescription", "type": "string" },
      { "selector": "trustChainConsensus", "text": "trustChainConsensus", "type": "string" },
      { "selector": "trustChainTrustScore", "text": "trustChainTrustScore", "type": "string" },
      { "selector": "type", "text": "type", "type": "string" }
     ],
     "source": "url",
     "type": "json",
     "url": "https://testnet-fullnode1.coti.io/transaction/lastTransactions",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "{container_name=\"coti-node\"} |= \"i.c.b.services.BaseNodeMonitorService \" != \"MonitorService is up\" | pattern `<_> Sources = <Sources>, DSPHealthState = <DSPHealthState>, DSPOutsideNormalCounter = <DSPOutsideNormalCounter>, TCCHealthState = <TCCHealthState>, TCCWaitingConfirmation = <TCCWaitingConfirmation>, TCCOutsideNormalCounter = <TCCOutsideNormalCounter>, PostponedTransactions = <PostponedTransactions>, PropagationQueue = <PropagationQueue>, WebSocketMessagesQueueLength = <WebSocketMessagesQueueLength>, waitingDspConsensus = <waitingDspConsensus>, confirmationQueueSize = <confirmationQueueSize>, percentageUsedHeapMemory = <percentageUsedHeapMemory>%, percentageUsedMemory = <percentageUsedMemory>%,`"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Recent Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{container_name=\"coti-node\"}"
    }
   ]
  },
  {
   "title": "Logs Volume",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({container_name=\"coti-node\"}[2m]))\n\n"
    }
   ]
  }
 ]
}